#pragma once
// Generated by build script, do not edit!
#define UNITY_VERSION_FULL "2018.2.1f1_1a9968d9f99c"
#define UNITY_VERSION_FULL_NICE "2018.2.1f1 (1a9968d9f99c)"
#define UNITY_VERSION_BLD 1743208
#define UNITY_VERSION_DATE 1531995848
#define UNITY_VERSION_WIN "2018.2.1.1743208"
#define UNITY_VERSION_BRANCH "2018.2/release"
